const FONT = "[font-family:'Plus_Jakarta_Sans',sans-serif]";
const tone = {
  cream: "bg-[#F7F2EF]",
  sage: "bg-[#E8F0EC]",
  blue: "bg-[#EAF0F5]",
  dark: "bg-[#20201E] text-white",
};

function Shell({ children }) {
  return <article className={`work-case-study h-full w-full min-w-0 max-w-full overflow-x-hidden overflow-y-auto bg-white text-[#171614] ${FONT}`}><div className="mx-auto w-full max-w-[1080px] px-5 py-10 sm:px-10 sm:py-16">{children}</div></article>;
}

function Hero({ role, brand, title, summary, detail, image, children }) {
  return <header className="grid gap-6 lg:grid-cols-[0.95fr_1.05fr] lg:gap-10">
    <Media src={image} alt={`${title} case study`} className="min-h-[330px] sm:min-h-[440px]" />
    <div className="flex min-w-0 flex-col justify-center rounded-[26px] bg-[#F7F2EF] p-7 sm:p-10">
      <p className="text-[12px] font-semibold uppercase tracking-[0.09em] text-[#B6632C]">{role}{brand && ` · ${brand}`}</p>
      <h1 className="mt-7 break-words text-[36px] font-medium leading-[1.06] tracking-[-0.05em] sm:text-[44px]">{title}</h1>
      <p className="mt-6 text-[19px] font-medium leading-[1.45] tracking-[-0.02em] text-[#332F2C]">{summary}</p>
      {detail && <p className="mt-4 text-[15px] leading-[1.7] text-[#6A625D]">{detail}</p>}
      {children}
    </div>
  </header>;
}

function Section({ eyebrow, title, intro, children, compact = false }) {
  return <section className={compact ? "py-10 sm:py-14" : "py-16 sm:py-24"}>
    <p className="text-[12px] font-semibold uppercase tracking-[0.09em] text-[#B6632C]">{eyebrow}</p>
    <h2 className="mt-4 max-w-[940px] text-[31px] font-medium leading-[1.12] tracking-[-0.045em] sm:text-[45px]">{title}</h2>
    {intro && <p className="mt-6 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C] sm:text-[19px]">{intro}</p>}
    {children && <div className="mt-10">{children}</div>}
  </section>;
}

function Media({ src, alt, className = "" }) {
  return <figure className={`flex min-w-0 items-center justify-center overflow-hidden rounded-[26px] bg-[#F4F0ED] ${className}`}><img src={src} alt={alt} className="h-full w-full object-contain" /></figure>;
}

function Grid({ children, cols = 2, className = "" }) {
  const layout = cols === 3 ? "sm:grid-cols-3" : cols === 4 ? "sm:grid-cols-2 lg:grid-cols-4" : "sm:grid-cols-2";
  return <div className={`grid gap-4 ${layout} ${className}`}>{children}</div>;
}

function Card({ title, children, variant = "cream" }) {
  return <div className={`rounded-[25px] p-6 sm:p-7 ${tone[variant] || tone.cream}`}><h3 className="text-[20px] font-semibold leading-[1.3] tracking-[-0.025em]">{title}</h3><div className="mt-4 space-y-3 text-[15px] leading-[1.7] text-[#665F5A]">{children}</div></div>;
}

function Stat({ value, children }) {
  return <div className="rounded-[25px] bg-[#F7F2EF] p-6 sm:p-7"><p className="text-[36px] font-medium tracking-[-0.05em] text-[#B6632C] sm:text-[44px]">{value}</p><p className="mt-4 text-[15px] leading-[1.65] text-[#665F5A]">{children}</p></div>;
}

function Quote({ children, name, role, dark = false }) {
  return <blockquote className={`rounded-[26px] p-7 sm:p-9 ${dark ? tone.dark : tone.cream}`}><p className={`text-[19px] leading-[1.6] sm:text-[22px] ${dark ? "text-white/90" : "text-[#322E2B]"}`}>“{children}”</p>{name && <footer className={`mt-7 text-[14px] ${dark ? "text-white/60" : "text-[#766D67]"}`}><strong className={dark ? "text-white" : "text-[#292623]"}>{name}</strong><br />{role}</footer>}</blockquote>;
}

function Link({ href, children }) {
  return <a href={href} target="_blank" rel="noreferrer" className="mt-7 inline-flex rounded-full bg-[#1D1D1B] px-5 py-3 text-[13px] font-semibold text-white transition hover:-translate-y-0.5">{children}<span className="ml-2">↗</span></a>;
}

const b2c = "/legacy/b2c/";
const service = "/legacy/service-design/";
const intent = "/legacy/intent/";
const ai = "/legacy/ai-search/";

export function B2CCaseStudy() {
  return <Shell>
    <Hero role="Lead designer" brand="Chase.com" title="Home Lending Public Experience" summary="Driving a 38% boost in conversions with need based segmentation" detail="Product strategy, Data-driven Design" image={`${b2c}01-ymR75kzrcRfz85kR75nKia3tc.png`}>
      <div className="flex flex-wrap gap-3"><Link href="https://www.chase.com/personal/mortgage">Landing Pages</Link><Link href="https://www.chase.com/personal/mortgage/calculators-resources/mortgage-calculator-b">Calculators</Link></div>
    </Hero>

    <Section eyebrow="Data discovery" title="High traffic — low conversion" intro="We were given raw data showing conversion rates at different touch points. What story does this tell? People visit but don't convert.">
      <p className="mb-8 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">I created this simple visualization to show the market we are missing. This helped illustrate the conversion bottleneck impact up to leadership and secured over $10,000 in investment for Home Lending Public experience re-design.</p>
      <Grid><Media src={`${b2c}02-4f1paTcLpwkR15o3RbyggwIz0s0.png`} alt="Conversion opportunity visualization" /><Media src={`${b2c}03-E4FnfyepYIjdwCLHI4nRzcN9TgQ.png`} alt="Conversion funnel analysis" /></Grid>
      <h3 className="mt-12 text-[26px] font-medium tracking-[-0.03em]">Deeper look at data</h3>
      <p className="mt-4 max-w-[850px] text-[17px] leading-[1.7] text-[#66605C]">Let's analyze the points of friction and the clicks to try to understand customer intent and needs</p>
      <Grid cols={3} className="mt-8">
        <Card title="KYC Flow"><p>“Start online” takes customers through an account creation flow with sensitive questions like SSN</p></Card>
        <Card title="Outdated design"><p>Over 800 public pages, lack of branding and 20+ CTAs with unclear pathways</p></Card>
        <Card title="Clicks"><p>Top clicks were for miscellaneous actions like hamburger menu, sign-in. The most desired (rates) was 4th click which is 3 scrolls below</p></Card>
      </Grid>
      <Media src={`${b2c}04-Lc5ekFyZ0kkSExMuDHkfFyyS1QA.png`} alt="Existing experience and points of friction" className="mt-8" />
    </Section>

    <Section eyebrow="Define" title="3-Day Design Workshop" intro="The design team led a one day workshop starting with blue sky thinking to get the group to step out of tech constraints, devise a clear vision to share with stakeholders and create a few designs to see our ideas live and plan the roadmap.">
      <Grid cols={3}><Media src={`${b2c}05-k0QzJIXZxHNx1fiyWSb3dFHRUSo.png`} alt="Workshop outputs" /><Media src={`${b2c}06-NJCEltAvgd1A8smKn4ussJR38I.jpeg`} alt="Design workshop" /><Media src={`${b2c}07-65FVv0GKSG3nRelBUiwgnNmqA.jpeg`} alt="Design workshop collaboration" /></Grid>
    </Section>

    <Section eyebrow="Research" title="Scenario mapping" intro="Applying the four forces model, we tried to understand what would push customers out of renting and pull them into the attractive new home. However, habits and anxieties can outweigh this.">
      <Media src={`${b2c}08-Y4f4MQy2jqxjZFsycjPANNzmE58.png`} alt="Four forces scenario mapping" />
      <h3 className="mt-12 text-[26px] font-medium tracking-[-0.03em]">Habits and anxieties</h3>
      <p className="mt-4 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">Customers might not see the value of buying a new home if they're comfortable renting. Even if they do want to buy a new home, they might be anxious about certain factors.</p>
      <p className="mt-4 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">Through customer research, we dived deep into these habits and anxieties such as credit concerns, need education before decision and importance of value before commitment</p>
      <Grid cols={3} className="mt-8"><Quote>I notice the apply button but I would definitely be spending more time in the learn before deciding to understand everything first</Quote><Quote>Just to understand the steps before I commit to clicking on the apply to buy button</Quote><Quote>I don't [feel ready] because I would want to consider my husband's finances as part of the loan and, um, we're still working over the next couple of months to get his credit to a better place</Quote></Grid>
      <h3 className="mt-12 text-[26px] font-medium tracking-[-0.03em]">Competitor Analysis</h3>
      <p className="mt-4 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">Competitors offered tailored resources and clear support for customers at every stage of the home buying journey, including prominent contact options. Rocket Mortgage stands out with more engaging and persuasive language.</p>
      <Media src={`${b2c}09-ODmhKRIvSI8ESteEPTykUhiPo.png`} alt="Competitor analysis" className="mt-8" />
    </Section>

    <Section eyebrow="Principles" title="Design values" intro="We set the values for our new design grounding in customer's thoughts, feelings and actions to understand both what we want and what we don't want">
      <Grid>
        <Card title="What we want" variant="sage"><p><strong>Think:</strong> Chase is reliable and offers clear options that fit my needs. I can make an informed decision if I am ready.</p><p><strong>Feel:</strong> Confident, reassured, and supported. Empowered to step into home ownership.</p><p><strong>Say:</strong> “I know what to do, this looks easy to start”</p><p><strong>Do:</strong> Use tools, start an application, reach out for help</p></Card>
        <Card title="What we don't want"><p><strong>Think:</strong> I don't know where to look, I am confused and distracted. This is complicated.</p><p><strong>Feel:</strong> Overwhelmed, anxious, or skeptical. Lose trust in Chase to help achieve home goals.</p><p><strong>Say:</strong> “This is too complicated.” “I’m not sure what to do.”</p><p><strong>Do:</strong> Leave the page, give up, or look elsewhere</p></Card>
      </Grid>
    </Section>

    <Section eyebrow="Strategy" title="Need-based segmentation" intro="This led us to create three customer segments based on needs and trust. We need to earn trust with early explorers, establish trust with rate shoppers, and keep trust with those ready to apply."><Media src={`${b2c}10-7M6K11H6e8xIaElT6qKiU1m7P4.png`} alt="Need-based segmentation strategy" /></Section>

    <Section eyebrow="Solution" title="Designing for each point of readiness">
      <div className="space-y-12">
        <div><h3 className="text-[27px] font-medium tracking-[-0.03em]">Ready to apply segment</h3><p className="mt-4 max-w-[850px] text-[17px] leading-[1.7] text-[#66605C]">“Start online” might get clicks, but customers who are actually ready to apply will click “Apply to buy”</p><p className="mt-3 max-w-[850px] text-[17px] leading-[1.7] text-[#66605C]">Value proposition “Our priority is you” with discounts and benefits to trust Chase</p><Media src={`${b2c}11-l9jPg2STWZZsm8B1eiK7ZNBG9ps.png`} alt="Ready to apply experience" className="mt-7" /></div>
        <div><h3 className="text-[27px] font-medium tracking-[-0.03em]">Rates as decision point</h3><p className="mt-4 max-w-[850px] text-[17px] leading-[1.7] text-[#66605C]">Rates was 4 scrolls below in the old page. New page has value (personalized) and rates in 1st scroll</p><p className="mt-3 max-w-[850px] text-[17px] leading-[1.7] text-[#66605C]">Clear branding (colors, warm tone images, no illustrations) and powerful content to imbibe trust in Chase</p><Media src={`${b2c}12-xPxcAuX1vCQDzANWabMsZeb3FA.png`} alt="Rates decision experience" className="mt-7" /></div>
        <div><h3 className="text-[27px] font-medium tracking-[-0.03em]">Shopping segment</h3><p className="mt-4 max-w-[850px] text-[17px] leading-[1.7] text-[#66605C]">Reduce CTA overload in new design with clear purposeful CTAs</p><p className="mt-3 max-w-[850px] text-[17px] leading-[1.7] text-[#66605C]">Mortgage calculator and affordability calculator highlighted with HLA guide section</p><Media src={`${b2c}13-xE6dos6mfQQCkqUOM8vpPEcBNDE.png`} alt="Shopping experience" className="mt-7" /></div>
        <div><h3 className="text-[27px] font-medium tracking-[-0.03em]">Early explorer segment</h3><p className="mt-4 max-w-[850px] text-[17px] leading-[1.7] text-[#66605C]">Top 3 action oriented educational articles rather than 7 hyperlinks</p><p className="mt-3 max-w-[850px] text-[17px] leading-[1.7] text-[#66605C]">No sticky footer forcing customers to “Start online” and apply</p><Media src={`${b2c}14-TD8YRxTjhJCBG3Sa2WIlJFsEgzY.png`} alt="Early explorer experience" className="mt-7" /></div>
      </div>
    </Section>

    <Section eyebrow="Impact" title="What changed after launch">
      <Grid cols={3}><Stat value="38%">Increase in lead initiate for variant CTA compared to control</Stat><Stat value="-0.5%">Reduced conversion in mobile - split flag issues and further investigation</Stat><Stat value="4%">Decrease in lead submit (conversion) in variant compared to control</Stat></Grid>
      <div className="mt-8"><Quote name="Bart Piela" role="Marketing/Public Executive Director" dark>Sanjana is the best designer at Chase that I've worked with. She is proactive, thoughtful, eager to learn and produces ideas and designs at both a high quality and high volume - which is rare! She has very high potential at Chase over a long runway. I am very thankful she is part of the CMH Marketing Quad; she makes it much stronger.</Quote></div>
    </Section>

    <Section eyebrow="Optimize" title="What happens after results?" intro="Based on data, we continued to make enhancements because we know that fixing the page doesn't fix the experience, so we continued momentum with more initiatives">
      <Grid><Card title="The next initiatives"><p>ECI cookie optimization for simple sign in for existing customer</p><p>Unified calculator to replace outdated iFrame (inaccessible by AI crawlers, poor usability).</p><p>Public design system for Home Lending in the new tech stack.</p></Card><Card title="Continuing the system"><p>Multi-variant testing for L2 navigation and decommission old HL public pages (~100)</p><p>Improve strategy for Paid Search, Paid Media and external aggregators</p><p><strong>Within a few sprints, we did it all</strong></p><p>With AI, we continue to evolve now building a search-optimized experience</p></Card></Grid>
      <Media src={`${b2c}15-qzuAceqxB3JlAh49a20hHH7R8M.png`} alt="Home Lending design system and optimized experience" className="mt-8" />
    </Section>
  </Shell>;
}

export function ServiceDesignCaseStudy() {
  return <Shell>
    <Hero role="Lead designer" brand="Chase MyHome" title="Apply & Self-service" summary="Mapping complex customer journeys, workflows, and backend systems. Created service-design blueprint." detail="Improve self-service experiences at scale." image={`${service}01-G9fAv4zfnXda5ghIjXZ3mSXe6hg.png`} />
    <Section eyebrow="Problem framing" title="Two sides of the story" intro="When we considered both sides of the problem, we were able to bridge the needs into an optimal solution for both the business and customers so it doesn't feel like a bank selling loans.">
      <Grid><Card title="Business side"><p><strong>Quality leads:</strong> Make revenue with customers loans that will benefit the business</p><p><strong>Technology:</strong> Limited by how much data about our customers we can leverage, pre-fill and suggest</p><p><strong>Cost-effective:</strong> We need to invest more in digital solutions than humans (Home Lending Advisors)</p></Card><Card title="Customer side" variant="sage"><p><strong>Financial commitment:</strong> This is a huge, once-in-a-lifetime financial commitment, customers need to trust the bank and have a long-term relationship</p><p><strong>Best deals:</strong> Customers need to get the best rates, personalized offers to make the right decision</p><p><strong>Support & guidance:</strong> Customers need help figuring out the process, what to expect, etc.</p></Card></Grid>
      <h3 className="mt-12 text-[27px] font-medium tracking-[-0.03em]">Insights</h3><p className="mt-4 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">Significantly high drop-offs on other pages notably employment, review page, co-applicant info, and surprisingly the landing page. Did customers not intend to apply?</p><p className="mt-3 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">Analyzing exit surveys, we were able to see why customers dropped after clicking apply</p>
      <Grid cols={3} className="mt-8"><Card title="Rates before apply"><p>See numbers, offers, and the best rate they can be financially confident</p></Card><Card title="Applying = committment"><p>Customers don't want a hard credit pull. Purchase customers are looking for preapproval</p></Card><Card title="Too much info & SSN"><p>The process of loan fulfillment is unclear and customers don't get why things are asked</p></Card></Grid>
    </Section>
    <Section eyebrow="Define" title="1-Week Discovery Workshop" intro="We conducted a workshop to deeply understand the problem with empathy mapping, prioritization matrix and assumption mapping ending with high level design concepts."><Grid cols={3}><Media src={`${service}02-ZFPRZ7LSTxEcd2CSnrId0r8sM.png`} alt="Discovery workshop" /><Media src={`${service}03-Hus5S94KZSHWRuKYgC0V0tN3D8.png`} alt="Discovery workshop collaboration" /><Media src={`${service}04-hWbZu3mILmurAxceD1HD8T3LjkU.png`} alt="Workshop mapping" /></Grid></Section>
    <Section eyebrow="Research" title="Into the customer's mind" intro="Through customer research, we dived deep into these habits and anxieties such as credit concerns, need education before decision and importance of value before commitment"><Media src={`${service}05-fCpiK06ogDAiR4oP3Zvumcd6tTY.png`} alt="Customer research findings" /></Section>
    <Section eyebrow="Strategy" title="Only ask for info after customer has experienced real value" intro="Customers expect Chase to have their data and know about them to give the best pricing and pre-fill details so they know what they're getting into before applying">
      <Grid cols={3}><Card title="Numbers"><p>Is this the right time?</p><p>Is this is the best rate for me?</p></Card><Card title="Personalized info"><p>Why Chase?</p><p>What do they offer?</p><p>What do they know about my home?</p></Card><Card title="Information"><p>What's the process?</p><p>Is it easy?</p><p>What can I expect?</p><p>What if I need help?</p></Card></Grid>
    </Section>
    <Section eyebrow="Service design" title="What runs behind the scenes?" intro={'I kept hearing "that’s not feasible" so I took time to create a service design blueprint to map all the backend implementations, services, HLA side and data downstream implication. This now became a living breathing document to find opportunities and close gaps.'}><Media src={`${service}06-UVlNnxS8OdmPfKYrIM6r4NlXE.png`} alt="Service design blueprint" /><h3 className="mt-12 text-[27px] font-medium tracking-[-0.03em]">Journey mapping</h3><p className="mt-4 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">Now that I understood the backend, I created a journey for a self-service experience. Considering both business and customers, I proposed self-service (for the business) but with guardrails for support IF and WHEN they need (for the customers).</p><Media src={`${service}07-t37f9WcLWqDcXNCHIzwZ64iwRy8.png`} alt="Self-service journey map" className="mt-8" /></Section>
    <Section eyebrow="0-to-1 solution" title="Engaging with rates before applying" intro={'We launched a new "HELOC rate tool" so that when customers apply, they can first see their estimated HELOC rate, eligibility for the product and a quick preview of loan option tailored to their information.'}><Media src={`${service}08-BJhHrTW7486jBDCSxVgJ0BZ1g0.png`} alt="HELOC rate tool experience" /><Grid className="mt-8"><Quote>It makes me feel good. It makes me feel like I don't have to provide this information…I'm applying for a loan from Chase, so they should already have the information. It shows that they're professional, and it also makes things quicker.</Quote><Quote>I thought that was great because it provided a quick snapshot... I also like the end summary because it was timely and told me what it would cover.</Quote></Grid></Section>
    <Section eyebrow="The application" title="Empowering with ease of application" intro="All the granular changes that led to improve in submit rate, reduced drop-offs and alleviated customer fears">
      <div className="space-y-12">
        <div><Card title="Powerful, goal-oriented"><p>We have mortgages for everyone's unique needs.</p><p>Goal based clear “Apply” buttons rather than “Get started” so the intent of initiating apply is clear</p></Card><Media src={`${service}09-yFWJIopXdaXOq5cQWJqgMSuB4.png`} alt="Goal-oriented mortgage entry points" className="mt-5" /></div>
        <div><Card title="Set expectations and confidence" variant="sage"><p>You may skip questions or estimate - info is not final</p><p>No hard credit check</p><p>Someone will help you after you apply</p></Card><Media src={`${service}10-jNarU319ulSuOW5YqJqPNNWHw.png`} alt="Application expectations and confidence" className="mt-5" /></div>
        <div><Card title="Conversational"><p>Less interrogative and more “simple” “easy” tone</p><p>Reducing redundant pages and re-framing address requirements</p></Card><Media src={`${service}11-YNgIKs4fgaiSiBETcCG5Ekgi9Y.png`} alt="Conversational application flow" className="mt-5" /></div>
        <div><Card title="Less inputs" variant="blue"><p>Highest drop-off page because we even ask for company address</p><p>Stripped it down to just employment status and optional details</p></Card><Media src={`${service}12-jPgyuhp98K52ZolLf6JB4q6YTE.png`} alt="Simplified employment inputs" className="mt-5" /></div>
        <div><Card title="Soft credit, SSN with purpose"><p>Influenced product decision to change to soft credit check</p><p>SSN only IF you say yes to soft credit check rather than as the 4th question of the flow</p></Card><Media src={`${service}13-ODot83UjosqtauKWb7g9dSvIXk.png`} alt="Soft credit and SSN permission" className="mt-5" /></div>
        <div><Card title="Explain why we ask & how info helps" variant="sage"><p>Info not final</p><p>One of the high drop off pages reduced to most important info surfaced and rest hidden</p><p>“Its okay to miss some details”</p></Card><Media src={`${service}14-vvrSTqYSTRKaqSf7od5tvnU4cn4.png`} alt="Application review and explanation" className="mt-5" /></div>
        <div><Card title="Efficient loan fulfillment"><p>Setting the stage for eventually creating a fully digital self-service platform. Leveraging better third party integration to show automated real-time updates on documents and tasks. Reduced cognitive load of documents by combining all read-only documents into one task with preview and number of docs.</p></Card><Grid className="mt-5"><Media src={`${service}15-Lc5ekFyZ0kkSExMuDHkfFyyS1QA.png`} alt="Loan fulfillment journey" /><Media src={`${service}16-JOBMM1bAY5wD6qiIQFvUSmzAT0.png`} alt="Final self-service experience" /></Grid></div>
      </div>
    </Section>
    <Section eyebrow="Impact" title="The result of making the journey clearer">
      <Grid cols={3}><Stat value="5.5%">Increase in lead submit after apply flow changes</Stat><Stat value="Credit concerns">Exit surveys reported lower concerns of credit pull</Stat><Stat value="208 leads">HELOC rate tool received 3.1k visits in 10% split with 43 apps</Stat></Grid>
      <Grid cols={3} className="mt-8"><Quote name="Sonia Zacheo" role="CMH Product VP">A very special call out and thank you to Sanjana for being such an amazing partner and consistently going above and beyond when it comes to projects we are working on. Sanjana has been instrumental in the Encompass build UX, providing solutions and quickly adjusting to our changing needs.</Quote><Quote name="Andrew Kennerley" role="Content VP">Sanjana! I wanted to send a special thanks for all your hard work, patience and collaboration this year! You jumped into the Apply world with both feet and I've loved exploring ways to improve our customers' experience. You approach every challenge or change in direction with a smile and you're open to everyone's feedback. Thank you for always being there and for being a wonderful teammate.</Quote><Quote name="Saurabh Shreedhar" role="AOA Product VP">Hello Sanjana, Samuel - This is to appreciate your efforts in running unmoderated customer research towards the discovery item for our AOA Home Lending flow. Amazing work, great insights and nicely presented. Hope to continue the wonderful partnership to deliver quality experience with customer focus in mind. Keep up the good work.</Quote></Grid>
      <Grid className="mt-8"><Quote>It’s nice that they kinda outlined…not just what you need but why do you need it...Because sometimes you don’t wanna provide personal information, so its good to justify every step of the way</Quote><Quote>It’s like keep calm carry on…I am a little confident... makes me wanna find out what my rates are..that I’ll hear from someone</Quote><Quote>I like that it says ‘it's okay to estimate and skip’ So don't feel like super committed…like this doesn't feel like it's gonna be such a big thing to go through this page</Quote><Quote>Breezed through some of the pages…felt like something that would not take too long…I liked that you can be detailed and thorough so you when you have the call it will be worthwhile..I liked the progress bar</Quote></Grid>
    </Section>
  </Shell>;
}

export function IntentCaseStudy() {
  return <Shell>
    <Hero role="Lead designer" brand="Chase MyHome" title="Intent-based recommendations" summary={'Years of customer data, but data alone couldn\'t answer “what does this customer actually need right now?”'} detail="I led the strategy behind a need-based recommendation framework that helped AI infer user intent before deciding what experience to show. Native Mobile. More Product Strategy, Data Science and Research" image={`${intent}01-ULRP0FZksJHUAfiiIvrdPTDdkE4.png`} />
    <Section eyebrow="Business problem" title="One-size fits all" intro="We had millions of customer data points, but every customer still saw essentially the same experience. CTR and Engagement on Chase MyHome was much lower than other tiles because we were recommending products instead of understanding customer intent.">
      <Grid cols={3}><Stat value="40%">Only 40% of customers who have a mortgage with Chase ever visit and engage with ChaseMyHome</Stat><Stat value="2.06%">The current click through rate (CTR) is much lower for Chase MyHome compared to other tiles</Stat><Stat value="5%">Out of 2M customers who have transacted (got a loan) with us, only 5% engaged with Chase MyHome 6 months prior to transcation</Stat></Grid>
      <Media src={`${intent}02-iva8IfQ52CLxUlzXZE5UHow6XFE.png`} alt="Existing one-size-fits-all experience" className="mt-8" />
      <h3 className="mt-12 text-[27px] font-medium tracking-[-0.03em]">Why does intent matter?</h3><p className="mt-4 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">Before recommendations, we wanted to understand how customers perceived personalization. The theme: people weren't asking for more marketing, they want us to understand their situation.</p><Grid className="mt-8"><Quote>I got an email yesterday about lowering my payment to 5% but I got my rate during the pandemic of 3%. So I don't know what CMS you guys use, but you might want to be more targeted</Quote><Quote>I got a video from Chase that addressed me by my name which made me inclined to watch it. It makes you feel special, candid… My mortgage company took the time to make me a little video. In a world where there's no customer service left, it felt nice to see that</Quote></Grid>
    </Section>
    <Section eyebrow="Discovery" title="1-Day Discovery Workshop" intro="The design team led a workshop bringing together product, tech and marketing stakeholders. The business goal was to increase engagement into Chase My Home (CTR) and increase applications (Lead initiate rate)">
      <Grid cols={3}><Card title="Business Goal"><p>The business goal was to increase engagement into Chase My Home (CTR) and increase applications (Lead initiate rate)</p></Card><Card title="Problem Discovery"><p>We did assumption mapping exercise for desirability (do people want it/need it), feasibility (can we do it) and viability (will it result in long-term profit)</p></Card><Card title="Use Cases"><p>We narrowed down a few use cases to start with so the backend team can plan parameters for recommendation model</p></Card></Grid><Grid className="mt-8"><Media src={`${intent}03-NJCEltAvgd1A8smKn4ussJR38I.jpeg`} alt="Discovery workshop" /><Media src={`${intent}04-65FVv0GKSG3nRelBUiwgnNmqA.jpeg`} alt="Workshop collaboration" /></Grid>
    </Section>
    <Section eyebrow="Research" title="Assumption Mapping" intro="Before building recommendations, we challenged every assumption around desirability, feasibility and business value. The goal wasn't to generate more messages. It was to make sure the system was making the right decision in the first place."><Grid cols={3}><Media src={`${intent}05-ObUPjHiF6JFeqKmCUP6pQWmDYvY.png`} alt="Assumption mapping" /><Media src={`${intent}06-9oM7OXoBQKt9wsNhkNGk0nEFPc.png`} alt="Assumption map detail" /><Media src={`${intent}07-2VmMxCm6VCt3IH0AxFvOkix8dM.png`} alt="Prioritized assumptions" /></Grid></Section>
    <Section eyebrow="Framework" title="Response framework" intro="At first, our thinking looked something like this. But two customers could look almost identical on paper while trying to accomplish completely different things.">
      <Media src={`${intent}08-Zeck9bin3pBmkpU6OYKCORmg1Qs.png`} alt="Response framework" />
      <Grid className="mt-8"><Card title="Currently, generic"><p>Let's say, John has a home and mortgage with Bank of America.</p><p>But regardless of what we might know about John’s home, we show one tile for all</p></Card><Card title="Now, relevant" variant="sage"><p>We use data and intelligence to predict relevant messaging</p><p>John has a good credit score and can qualify for offers since he has been doing his monthly payments on time</p></Card></Grid>
      <Grid className="mt-5"><Media src={`${intent}09-C2XStsxJenvpOyGEhqArlgECcNA.png`} alt="Current generic recommendation" /><Media src={`${intent}10-m78VUILEi5Otqglb7ji6cSsuA.png`} alt="Relevant recommendation" /></Grid>
      <h3 className="mt-12 text-[27px] font-medium tracking-[-0.03em]">But what if John doesn't want to refinance?</h3><p className="mt-4 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">What if John wants to get cash and HELOC is better? Or pay off mortgage sooner so he can retire? Or buy a second home because he wants an investment property?</p><p className="mt-4 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">If we only market a rate & term refinance to this customer based on data 30 days ago, they might be high propensity for refinance but still not click on it due to different goals. To be timely and goal-oriented, we proposed a dynamic approach to personalization.</p><Grid className="mt-8"><Media src={`${intent}11-Hc83uU5EEBAhD081fldnvZKk7os.png`} alt="Different customer needs" /><Media src={`${intent}12-k8miWRxVaTIiWv0HDFW17ixKc.png`} alt="Dynamic personalized recommendation" /></Grid>
      <h3 className="mt-12 text-[27px] font-medium tracking-[-0.03em]">The proposal</h3><p className="mt-4 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">What if we tracked recent data and behavioral indicators that indicate intent and show dynamic tiles to understand customers' needs rather than only selling one product like refinance?</p>
    </Section>
    <Section eyebrow="Reasoning layer" title="Intent Classification Framework" intro={'The model shouldn\'t ask “who is John?” and gather all the data. The model should ask, “what is John trying to accomplish today?”'}><p className="mb-8 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">Rather than organizing recommendations around products, I organized them around customer needs. Each need mapped to readiness signals, available data and an appropriate messaging strategy.</p><Media src={`${intent}13-5n6T6sd0EjkDCh9hn214Pktu20.png`} alt="Intent classification framework" /></Section>
    <Section eyebrow="Roadmap & prioritization" title="Operationalizing the framework" intro="The proposal became our north star, and for now based on customer segments, existing and new data features in the SONAR model we created 6 use cases for MVP."><p className="mb-8 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">For the top decile customers (ready to apply), we had most data on as they had a mortgage and were buying their second home (common use case) or refinancing. The last two use cases were for nurturing our low decile customers (explorers) to improve return rate and engagement.</p><Grid><Media src={`${intent}14-OmcrzdW6uWCCxnrt01G1N3wpnI.png`} alt="MVP use cases roadmap" /><Media src={`${intent}15-5iqfLJ51gnDFfLFlq4sP2ckrCy8.png`} alt="Use case prioritization" /></Grid></Section>
    <Section eyebrow="Validation" title="Validating decision framework" intro="Utility score analysis: When it comes to how much customers care about their choice, images and stand out. Customers don’t just pick these two more often, they feel much more strongly about their preference for them compared to the rest. The higher utility scores (1.7 and 1.36) show that these images spark real enthusiasm, while others lag behind or even get negative reactions.">
      <p className="mb-8 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">It’s all about picking the best mix. If we just use images 5 and 7, we reach about 42% of customers. But when we add Images and 6 to the lineup, our reach jumps to 74%. By optimizing the image selection based on customers’ first choice, we can connect with as many people as possible.</p>
      <Grid cols={3}><Media src={`${intent}16-Sc4IgTjfcYuOD4ocx648Mylgj8.png`} alt="Utility score analysis" /><Media src={`${intent}17-COkXf3EZW08h5scTgSkZSjEik.png`} alt="Tested image options" /><Media src={`${intent}18-InBKqP5UMEH5YqVWfwKDRGoG2o.png`} alt="Cumulative customer reach" /></Grid>
      <Grid className="mt-8"><Card title="Positive feelings" variant="sage"><p><strong>Family/Togetherness:</strong> “They center the family and they reflect myself and when I think of the driving factor to own a home I think of my family eating in the kitchen, running in the yard, and creating memories.”</p><p><strong>Relatability/Life stage:</strong> “I relate to images as they portray my personal life. For example, I am married so I liked the beautiful couple,”</p><p><strong>Aspirational/Milestone:</strong> “The concept of a new house, whether it be one being built, or one with the for-sale sign. Smiling faces also make a difference.”</p><p><strong>Positive feeling:</strong> “I really thought it was a sweet image that kind of tugged on my heartstrings and makes me feel good about seeing it.”</p></Card><Card title="Negative feelings"><p><strong>Relatability/Life stage:</strong> “I don't have children so I can't really connect to any pictures with them. I certainly can't connect to any pictures that have children with grandparents.”</p><p><strong>Stock:</strong> “Least preferred the images that felt posed and had a stock photography nature. These felt inauthentic and like models on a set rather than a real family I could relate to.”</p><p><strong>Stressful:</strong> “I don't like seeing boxes, because I don't like packing or unpacking.”</p><p><strong>Home style:</strong> “The homes that are literally on top of one another. It is the opposite of what we are looking for in our next home.”</p></Card></Grid>
      <Grid cols={3} className="mt-8"><Media src={`${intent}19-dsngrgaO7JT20OCJm8RG1pMP0M.png`} alt="Validation decision flow" /><Media src={`${intent}20-FmI3JCluVAkBzdYOzQv8X4bGza4.png`} alt="Combined validation analysis" /><Media src={`${intent}21-EscmwdmZQFyNNtLca1uugmXKio.png`} alt="Reach analysis" /></Grid>
    </Section>
    <Section eyebrow="Experimentation model" title="Framework to production" intro="I implemented the latest atomic design composable library with my devs on native IOS, android and web. Engineering translated the framework into a reusable experimentation model where different signals could trigger different recommendation strategies while remaining easy to scale."><Grid><Media src={`${intent}22-OzJdWgfknQ98mh3BIOn1I8aSI0.png`} alt="Current recommendation state" /><Media src={`${intent}23-PBFtyxEaSfKfpRiMnveD3IEyr60.png`} alt="Proposed experimentation model" /></Grid><Grid cols={3} className="mt-5"><Media src={`${intent}24-p9yTAjfjheCYVsFcwTurs0KGdic.png`} alt="SONAR model card" /><Media src={`${intent}25-yVr30ITfogODvAuOzXECkY5J04k.png`} alt="Recent data signals" /><Media src={`${intent}26-mLkdwJEZnMzhAgIiofVsa9ixzYQ.png`} alt="Timely relevant tile" /></Grid></Section>
    <Section eyebrow="Impact" title="Understanding intent increased engagement" intro="This project completely changed how I think about personalization. I realized the hardest problem wasn't generating content. It was deciding what should be generated in the first place."><Grid><Stat value="17%">Increase in CTR for the first first variant with house imagery</Stat><Stat value="Lead submit rate">Not mature data yet about lead submit rate and lead initiate rate</Stat></Grid></Section>
  </Shell>;
}

export function AISearchCaseStudy() {
  return <Shell>
    <Hero role="Designer" title="AI Search Interfaces" summary="As ChatGPT and Gemini become the first place people ask financial questions, I explored what the model should do, how to move people to action, what should stay inside trusted banking systems." detail="Visionary concepts, executive leadership pitch" image={`${ai}01-ok2FwLhpQVwF3DD3NzVjcxrqtjs.png`}><Link href="https://www.figma.com/proto/AfdMacVC1hxCatMSBxZkPU/WE-Hack-2023?node-id=63-1430&starting-point-node-id=63%3A1430&t=wH2tCwdexzK4CqBj-1">See Gemini/ChatGPT prototype</Link></Hero>
    <Section eyebrow="Problem" title="The shift" intro={'Customers aren\'t starting financial journeys in banking apps anymore. They\'re asking ChatGPT and Gemini first. So instead of asking “How do we build another AI assistant?”'}><p className="max-w-[900px] text-[20px] font-medium leading-[1.6] text-[#332F2C]">I started asking: What should the model answer? What information should it gather? When should it recommend? When should it ask another question? When should it hand off to Chase?</p><p className="mt-5 max-w-[900px] text-[17px] leading-[1.7] text-[#66605C]">That became the framework for every concept.</p><p className="mt-8 max-w-[900px] text-[25px] font-medium leading-[1.4] tracking-[-0.03em]">How might we define the right role for AI in high-trust financial decisions without interrupting the conversation?</p></Section>
    <Section eyebrow="Principles" title="Search is should be action-oriented" intro="Users aren't just looking for information, they also want to do something with it. AI changes search from navigation to execution."><Grid cols={3}><Card title="Intent"><p>Model shouldn't immediately answer.</p><p>First understand what the customer is trying to accomplish.</p></Card><Card title="AI's boundaries"><p>AI shouldn't do everything.</p><p>The goal is knowing when AI should answer and when trusted banking systems should take over.</p></Card><Card title="Closer to action" variant="sage"><p>Each interaction should focus on a single action or outcome</p><p>Recommendations are only useful to take users to the next step.</p></Card></Grid></Section>
    <Section eyebrow="Considerations" title="Questions we kept asking"><div className="grid gap-3"><Card title="When should AI answer versus ask another question?" /><Card title="When should AI continue the conversation versus hand off?" /><Card title="What information is enough before recommending an action?" /><Card title="How do we keep trust while reducing friction?" /></div><Media src={`${ai}02-25WhZJSmrMK0G7FEahIFObZUF0.png`} alt="AI search workshop questions" className="mt-8" /></Section>
    <Section eyebrow="Model behavior" title="Why ChatGPT?" intro="The entire flow relies on user-owned documents, public data, and existing relationships, making it both realistic and low-risk to complete inside an AI interface."><Grid cols={3}><Card title="Fixing a real, time-sensitive gap"><p>When buyers need a lower pre-approval letter while actively house shopping (often on weekends), ChatGPT updates the letter instantly which is a task HLAs can’t handle in real time and current Chase app doesn't support digitally</p></Card><Card title="Making the offer smarter"><p>Using public neighborhood and market data, ChatGPT explains why lowering the pre-approval can improve offer strength, then evaluates the likelihood of acceptance and recommends tactics like an escalation clause</p></Card><Card title="Executing without friction" variant="sage"><p>ChatGPT drafts the escalation clause and offer letter and sends it to the HLA or realtor using existing contacts, turning search-time intent into immediate action without leaving ChatGPT.</p></Card></Grid><Media src={`${ai}03-S0A2aSckPEQeIkQp4e7aVVztlcg.jpeg`} alt="Team presenting AI search concept" className="mt-8" /></Section>
    <Section eyebrow="Model behavior" title="Why Gemini?" intro="Gemini supports exploration; Chase owns execution. Together, they show how AI search can safely evolve into real financial action. So the handoff is a trust decision."><Grid cols={3}><Card title="Starting with curiosity"><p>Gemini is good at helping people explore. Someone can upload a photo of a home, ask questions naturally, and connect that conversation to broader financial goals before deciding to take action.</p></Card><Card title="A deliberate shift to a trusted system"><p>When the task requires private financial data, Gemini hands off to the Chase app, which we reimagined as a conversational AI experience for all banking needs.</p></Card><Card title="Chase proactively turns interest into action" variant="sage"><p>Chase AI analyzes down payment readiness, suggests concrete actions to increase buying power, checks credit eligibility, prepares required documents, and schedules an advisor, all through conversation.</p></Card></Grid><Media src={`${ai}04-OYEkdgibcyKuscc4fzvTxM7RGlU.png`} alt="Gemini to Chase trusted handoff" className="mt-8" /></Section>
    <Section eyebrow="Reflection" title="What did I learn?" intro="This wasn't an exercise in redesigning ChatGPT. It was a strategy sprint to answer a much harder question: what role should AI play in one of the biggest financial decisions of someone's life?"><Grid><Card title="AI removes timing gaps"><p>AI is very valuable when it removes timing gaps. The biggest unlock wasn’t smarter answers, but eliminating real-world delays (like weekend availability or manual processes).</p></Card><Card title="Search becomes accountable action" variant="sage"><p>The future of search is accountable action. AI search only earns trust when it leads to clear next steps, ownership, and outcomes, not just recommendations.</p></Card><Card title="Trust is a design boundary"><p>Deciding when to stay inside an AI interface versus handing off to a secure system was a core UX decision.</p></Card><Card title="Intent matters more than interface" variant="blue"><p>Designing around what users are trying to accomplish. This creates more natural, scalable interaction patterns.</p></Card></Grid></Section>
  </Shell>;
}
